
; org-mode
(add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
; (transient-mark-mode 1)
; http://orgmode.org/org.html#TODO-Items
(setq org-log-done 'time)
(setq org-log-done 'note)
; no titles on pages generated by org-mode in latex
(setq org-export-latex-title-command "")
; include entries from the Emacs diary into Org-mode's agenda
(setq org-agenda-include-diary t)
; make README files use org-mode
(add-to-list 'auto-mode-alist '("README$" . org-mode))
; screw fundamental-mode. I'm going org!
(setq default-major-mode 'org-mode)
(setq org-export-kill-product-buffer-when-displayed t)

;; (setq org-ditaa-jar-path "/usr/share/org-mode/scripts/ditaa.jar" )
;; (require 'org-babel-init)                                                                                                                                                         
;; (require 'org-babel-ditaa)                                                                                                                                                        

; http://article.gmane.org/gmane.emacs.orgmode/11020
(setq org-agenda-ndays 1)                   ; I like daily agenda
(setq org-agenda-skip-deadline-if-done t)
(setq org-agenda-skip-scheduled-if-done t)
(setq org-agenda-use-time-grid nil)         ; No need for the scheduling


; http://home.fnal.gov/~neilsen/notebook/emacs.html
(require 'org-export-latex)
(add-to-list 'org-export-latex-classes 
'("smarticle" 
 "\\documentclass[10pt]{article} 
\\usepackage[utf8]{inputenc} 
\\usepackage[T1]{fontenc} 
\\usepackage{graphicx} 
\\usepackage{longtable} 
\\usepackage{hyperref}
\\usepackage[left=1in,top=1in,right=1in,bottom=1in,head=0.2in,foot=0.2in]{geometry}" 
 ("\\section{%s}" . "\\section*{%s}") 
 ("\\subsection{%s}" . "\\subsection*{%s}") 
 ("\\subsubsection{%s}" . "\\subsubsection*{%s}") 
     ("\\paragraph{%s}" . "\\paragraph*{%s}") 
     ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))



;; (setq org-publish-project-alist
;;       '(
;;        
;;        
;;         ("ruf"
;;          :base-directory "~/Documents/HomeSecurity/RufSpecs/"
;;          :auto-index nil ; don't generate index.org
;;          :recursive t
;;          :base-extension "org"
;;          :publishing-function org-publish-org-to-pdf
;;          :table-of-contents nil
;;          :headline-levels 3
;;          :auto-preamble t )
;;        
;;         )
;;       )


;; ;; remem
;; (load "remem.el")
;; (setq remem-prog-dir "/usr/bin")
;; (setq remem-database-dir "/home/amoore/RA-indexes")
;; (setq remem-scopes-list '(("mail" 6 5 500)
;;                           ("docs" 2 10 500)))

;; http://sachachua.com/wp/2008/01/13/capturing-notes-with-remember/
(setq remember-data-file "~/docs/remember.txt")
;;(global-set-key (kbd "C-c r") 'remember)

(autoload 'remember "remember" nil t)
(autoload 'remember-region "remember" nil t)

;; http://members.optusnet.com.au/~charles57/GTD/mydotemacs.txt
(setq org-directory "~/Documents/Agendas")
(setq org-default-notes-file "~/Documents/Agendas/notes.org")
(setq org-remember-default-headline "INBOX")
(setq remember-annotation-functions '(org-remember-annotation))
(setq remember-handler-functions '(org-remember-handler))
(add-hook 'remember-mode-hook 'org-remember-apply-template)
(define-key global-map "\C-cr" 'org-remember)

(setq org-remember-templates
      '(
        ("Todo" ?t "* TODO %^{Brief Description} %^g%?\nAdded: %U" "daily.org" "INBOX")
        ; ("Private" ?p "\n* %^{topic} %T \n%i%?\n" "C:/charles/gtd/privnotes.org")
        ; ("WordofDay" ?w "\n* %^{topic} \n%i%?\n" "C:/charles/gtd/wotd.org")
        ))



(setq muse-project-alist
      '(("WikiPlanner"
	 ("~/Plans"   ;; Or wherever you want your planner files to be
	  :default "index"
	  :major-mode planner-mode
	  :visit-link planner-visit-link))))
(require 'planner)

